from django.urls import path, include
from .views import (
    UserProfileListAPIView,
    UserProfileDetailAPIView,
    UserProfilePostsAPIView,
    UserFollowersAPIView,
    UserFollowingAPIView,
    UserFollowAPIView,
    UserUnfollowAPIView,
    PostListAPIView,
    PostDetailAPIView,
    PostCreateAPIView,
    PostLikeAPIView,
    PostSaveAPIView,
    PostCommentsAPIView,
    CommentListAPIView,
    CommentCreateAPIView,
    CommentDetailAPIView,
    CommentLikeAPIView,
    HashtagListAPIView,
    HashtagDetailAPIView,
    HashtagPostsAPIView,
    SavedPostsListAPIView,
    StoriesListAPIView,
    StoriesCreateAPIView,
    StoriesDetailAPIView,
    FollowingStoriesAPIView,
    RegisterView, LoginView, LogoutView,
)

urlpatterns = [
    path('users/', UserProfileListAPIView.as_view(), name='user-list'),
    path('users/<int:pk>/', UserProfileDetailAPIView.as_view(), name='user-detail'),
    path('users/<int:pk>/posts/', UserProfilePostsAPIView.as_view(), name='user-posts'),
    path('users/<int:pk>/followers/', UserFollowersAPIView.as_view(), name='user-followers'),
    path('users/<int:pk>/following/', UserFollowingAPIView.as_view(), name='user-following'),
    path('users/<int:pk>/follow/', UserFollowAPIView.as_view(), name='user-follow'),
    path('users/<int:pk>/unfollow/', UserUnfollowAPIView.as_view(), name='user-unfollow'),
    path('posts/', PostListAPIView.as_view(), name='post-list'),
    path('posts/create/', PostCreateAPIView.as_view(), name='post-create'),
    path('posts/<int:pk>/', PostDetailAPIView.as_view(), name='post-detail'),
    path('posts/<int:pk>/like/', PostLikeAPIView.as_view(), name='post-like'),
    path('posts/<int:pk>/save/', PostSaveAPIView.as_view(), name='post-save'),
    path('posts/<int:pk>/comments/', PostCommentsAPIView.as_view(), name='post-comments'),
    path('comments/', CommentListAPIView.as_view(), name='comment-list'),
    path('comments/create/', CommentCreateAPIView.as_view(), name='comment-create'),
    path('comments/<int:pk>/', CommentDetailAPIView.as_view(), name='comment-detail'),
    path('comments/<int:pk>/like/', CommentLikeAPIView.as_view(), name='comment-like'),
    path('hashtags/', HashtagListAPIView.as_view(), name='hashtag-list'),
    path('hashtags/<int:pk>/', HashtagDetailAPIView.as_view(), name='hashtag-detail'),
    path('hashtags/<int:pk>/posts/', HashtagPostsAPIView.as_view(), name='hashtag-posts'),
    path('saved/', SavedPostsListAPIView.as_view(), name='saved-posts'),
    path('stories/', StoriesListAPIView.as_view(), name='stories-list'),
    path('stories/create/', StoriesCreateAPIView.as_view(), name='stories-create'),
    path('stories/<int:pk>/', StoriesDetailAPIView.as_view(), name='stories-detail'),
    path('stories/following/', FollowingStoriesAPIView.as_view(), name='following-stories'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]